### ISSUE TITLE
App Store Rejection

### ISSUE THREAD

**Issue by MattCheetham** [3sidedcube/ThunderBasics#6]
> Your app uses or references the following non-public APIs:
> 
> parentAnnotation, 
> serviceIdentifier, 
> setParentAnnotation:
> 
> The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

**Comment by simonmitchell** [comment]
Quite like `superAnnotation` to go along with `UIView`'s `superView` e.t.c. :)
